# Generated by Django 4.1.3 on 2022-11-30 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Paper',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('link', models.CharField(max_length=255)),
                ('summary', models.TextField()),
                ('title', models.CharField(max_length=255)),
                ('authors', models.CharField(max_length=255)),
                ('date', models.DateField()),
                ('areas', models.CharField(max_length=255)),
                ('fields', models.CharField(max_length=255)),
                ('subjects', models.CharField(max_length=255)),
                ('name', models.CharField(max_length=255)),
                ('state', models.CharField(max_length=255)),
            ],
            options={
                'verbose_name_plural': 'papers',
            },
        ),
    ]
