# Generated by Django 4.1.3 on 2022-11-30 12:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('papers', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='paper',
            name='name',
        ),
        migrations.RemoveField(
            model_name='paper',
            name='state',
        ),
    ]
